"""Regenerate schema_catalog.json and load_v2_all.gsql from the GSQL DDL.

The DDL files (01_vertices.gsql, 02_edges.gsql) are the single authority; the
typed attribute catalog (used by the ingestion upsert to cast values) and the
bulk loading job are DERIVED from them by this script, so they cannot drift.
Run after any schema change:  python scripts/generate_schema_artifacts.py
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

SCHEMA_DIR = Path("docs/tigergraph_foundation/tigergraph/schema")
LOADING_JOB = Path("docs/tigergraph_foundation/tigergraph/loading/jobs/load_v2_all.gsql")
PREFIX = "phx_dm_v2_"
GRAPH = "iperform_v2_revenue"


def _strip_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    return re.sub(r"//[^\n]*", "", text)


def parse_vertices(text: str) -> dict[str, dict]:
    vertices: dict[str, dict] = {}
    for match in re.finditer(
        r"CREATE VERTEX\s+(\w+)\s*\((.*?)\)\s*WITH", _strip_comments(text), re.S
    ):
        name, body = match.group(1), match.group(2)
        primary = None
        attributes: dict[str, str] = {}
        for part in re.split(r",(?![^(]*\))", body):
            part = part.strip()
            if not part:
                continue
            pm = re.match(r"PRIMARY_ID\s+(\w+)\s+(\w+)", part)
            if pm:
                primary = {"name": pm.group(1), "type": pm.group(2)}
                attributes[pm.group(1)] = pm.group(2)
                continue
            am = re.match(r"(\w+)\s+(\w+)", part)
            if am:
                attributes[am.group(1)] = am.group(2)
        vertices[name] = {"primary_id": primary, "attributes": attributes}
    return vertices


def parse_edges(text: str) -> dict[str, dict]:
    edges: dict[str, dict] = {}
    for match in re.finditer(
        r"CREATE DIRECTED EDGE\s+(\w+)\s*\(\s*FROM\s+(\w+)\s*,\s*TO\s+(\w+)\s*\)"
        r"\s*WITH\s+REVERSE_EDGE=\"(\w+)\"",
        _strip_comments(text),
    ):
        edges[match.group(1)] = {
            "from": match.group(2),
            "to": match.group(3),
            "reverse_edge": match.group(4),
        }
    return edges


def write_catalog(vertices: dict, edges: dict) -> None:
    catalog = {
        "graph": GRAPH,
        "prefix": PREFIX,
        "vertex_count": len(vertices),
        "edge_count": len(edges),
        "vertices": vertices,
        "edges": edges,
    }
    path = SCHEMA_DIR / "schema_catalog.json"
    path.write_text(json.dumps(catalog, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {path}: {len(vertices)} vertices, {len(edges)} edges")


def write_loading_job(vertices: dict, edges: dict) -> None:
    short = lambda name: name[len(PREFIX):]  # noqa: E731
    lines = [
        "// iPerform V2 — loading job (GENERATED by scripts/generate_schema_artifacts.py",
        "// from 01_vertices.gsql + 02_edges.gsql — do not edit by hand).",
        "// File paths are relative to the data set root (data/sample or data/real).",
        "// RESTPP/pyTigerGraph upsert is the primary load path on the client machine",
        "// (no server-side file access); this job is the bulk-load alternative for a",
        "// host with local file access.",
        f"USE GRAPH {GRAPH}",
        "",
        f"CREATE LOADING JOB load_v2_all FOR GRAPH {GRAPH} {{",
    ]
    for name in vertices:
        lines.append(f'    DEFINE FILENAME f_{short(name)} = "./vertices/{short(name)}.csv";')
    for name in edges:
        lines.append(f'    DEFINE FILENAME f_{short(name)} = "./edges/{short(name)}.csv";')
    lines.append("")
    for name, spec in vertices.items():
        cols = ", ".join(f'$"{c}"' for c in spec["attributes"])
        lines.append(
            f"    LOAD f_{short(name)} TO VERTEX {name} VALUES ({cols}) "
            'USING HEADER="true", SEPARATOR=",";'
        )
    for name in edges:
        lines.append(
            f'    LOAD f_{short(name)} TO EDGE {name} VALUES ($"from_id", $"to_id") '
            'USING HEADER="true", SEPARATOR=",";'
        )
    lines.append("}")
    LOADING_JOB.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {LOADING_JOB}")


def main() -> int:
    vertices = parse_vertices((SCHEMA_DIR / "01_vertices.gsql").read_text(encoding="utf-8"))
    edges = parse_edges((SCHEMA_DIR / "02_edges.gsql").read_text(encoding="utf-8"))
    problems = [n for n, s in vertices.items() if not s["primary_id"]]
    problems += [n for n in list(vertices) + list(edges) if not n.startswith(PREFIX)]
    for name, spec in vertices.items():
        if "data_source" not in spec["attributes"]:
            problems.append(f"{name}: missing data_source")
    if problems:
        print("SCHEMA PROBLEMS:", problems)
        return 1
    write_catalog(vertices, edges)
    write_loading_job(vertices, edges)
    return 0


if __name__ == "__main__":
    sys.exit(main())
