"""Regenerate schema_catalog.json, load_v2_all.gsql and 90_drop_all.gsql from
the GSQL DDL.

The DDL files (01_vertices.gsql, 02_edges.gsql) are the single authority; the
typed attribute catalog (used by the ingestion upsert to cast values), the bulk
loading job AND the full-schema drop script (R6 B1) are DERIVED from them by
this script, so they cannot drift.
Run after any schema change:  python scripts/generate_schema_artifacts.py
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

SCHEMA_DIR = Path("docs/tigergraph_foundation/tigergraph/schema")
LOADING_JOB = Path("docs/tigergraph_foundation/tigergraph/loading/jobs/load_v2_all.gsql")
PREFIX = "phx_dm_v2_"
GRAPH = "iperform_v2_revenue"


def _strip_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    return re.sub(r"//[^\n]*", "", text)


def parse_vertices(text: str) -> dict[str, dict]:
    vertices: dict[str, dict] = {}
    for match in re.finditer(
        r"CREATE VERTEX\s+(\w+)\s*\((.*?)\)\s*WITH", _strip_comments(text), re.S
    ):
        name, body = match.group(1), match.group(2)
        primary = None
        attributes: dict[str, str] = {}
        for part in re.split(r",(?![^(]*\))", body):
            part = part.strip()
            if not part:
                continue
            pm = re.match(r"PRIMARY_ID\s+(\w+)\s+(\w+)", part)
            if pm:
                primary = {"name": pm.group(1), "type": pm.group(2)}
                attributes[pm.group(1)] = pm.group(2)
                continue
            am = re.match(r"(\w+)\s+(\w+)", part)
            if am:
                attributes[am.group(1)] = am.group(2)
        vertices[name] = {"primary_id": primary, "attributes": attributes}
    return vertices


def parse_edges(text: str) -> dict[str, dict]:
    edges: dict[str, dict] = {}
    for match in re.finditer(
        r"CREATE DIRECTED EDGE\s+(\w+)\s*\(\s*FROM\s+(\w+)\s*,\s*TO\s+(\w+)\s*\)"
        r"\s*WITH\s+REVERSE_EDGE=\"(\w+)\"",
        _strip_comments(text),
    ):
        edges[match.group(1)] = {
            "from": match.group(2),
            "to": match.group(3),
            "reverse_edge": match.group(4),
        }
    return edges


def write_catalog(vertices: dict, edges: dict) -> None:
    catalog = {
        "graph": GRAPH,
        "prefix": PREFIX,
        "vertex_count": len(vertices),
        "edge_count": len(edges),
        "vertices": vertices,
        "edges": edges,
    }
    path = SCHEMA_DIR / "schema_catalog.json"
    path.write_text(json.dumps(catalog, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {path}: {len(vertices)} vertices, {len(edges)} edges")


def write_loading_job(vertices: dict, edges: dict) -> None:
    short = lambda name: name[len(PREFIX):]  # noqa: E731
    lines = [
        "// iPerform V2 — loading job (GENERATED by scripts/generate_schema_artifacts.py",
        "// from 01_vertices.gsql + 02_edges.gsql — do not edit by hand).",
        "// File paths are relative to the data set root (data/sample or data/real).",
        "// RESTPP/pyTigerGraph upsert is the primary load path on the client machine",
        "// (no server-side file access); this job is the bulk-load alternative for a",
        "// host with local file access.",
        f"USE GRAPH {GRAPH}",
        "",
        f"CREATE LOADING JOB load_v2_all FOR GRAPH {GRAPH} {{",
    ]
    for name in vertices:
        lines.append(f'    DEFINE FILENAME f_{short(name)} = "./vertices/{short(name)}.csv";')
    for name in edges:
        lines.append(f'    DEFINE FILENAME f_{short(name)} = "./edges/{short(name)}.csv";')
    lines.append("")
    for name, spec in vertices.items():
        cols = ", ".join(f'$"{c}"' for c in spec["attributes"])
        lines.append(
            f"    LOAD f_{short(name)} TO VERTEX {name} VALUES ({cols}) "
            'USING HEADER="true", SEPARATOR=",";'
        )
    for name in edges:
        lines.append(
            f'    LOAD f_{short(name)} TO EDGE {name} VALUES ($"from_id", $"to_id") '
            'USING HEADER="true", SEPARATOR=",";'
        )
    lines.append("}")
    LOADING_JOB.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {LOADING_JOB}")


def write_drop_script(vertices: dict, edges: dict, queries: list[str]) -> None:
    """R6 B1 — the full-schema drop, in the ONLY order TigerGraph accepts:
    queries -> graph -> reverse edges -> forward edges -> vertices.

    Two live-box lessons encoded here (Round 5 shipped this wrong):
    1. A graph cannot be dropped while its queries exist — queries first.
    2. Reverse edges (WITH REVERSE_EDGE="...") are SEPARATE schema objects and
       do NOT drop with their parent edge — each needs its own DROP EDGE.
    """
    path = SCHEMA_DIR / "90_drop_all.gsql"
    lines = [
        "// iPerform V2 — FULL SCHEMA DROP (GENERATED by scripts/generate_schema_artifacts.py",
        "// from 01_vertices.gsql + 02_edges.gsql + query_catalog.json — do not edit by hand).",
        "//",
        "// NEEDS-LIVE-VERIFICATION: GSQL in this repo is parse-reasoned, never executed",
        "// here. Do not consider this script verified until it has run on the live box.",
        "//",
        "// Order is mandatory (TigerGraph refuses otherwise):",
        "//   1. queries        — a graph cannot be dropped while its queries exist",
        "//   2. the graph      — releases the schema objects",
        "//   3. reverse edges  — SEPARATE objects (WITH REVERSE_EDGE=...); they do NOT",
        "//                       drop with their parent edge",
        "//   4. forward edges",
        "//   5. vertices",
        "//",
        "// Expected vs real errors: on a partially-created schema, \"... does not exist\"",
        "// messages are EXPECTED and safe — GSQL reports them and continues. A",
        "// \"... is still in use\" / \"cannot be dropped\" message is a REAL failure:",
        "// something above it in this order was skipped — stop and investigate.",
        "//",
        "// Run:      gsql 90_drop_all.gsql",
        "// Recreate: gsql 01_vertices.gsql && gsql 02_edges.gsql && gsql 03_create_graph.gsql",
        "//           && gsql ../queries/install_all_queries.gsql",
        "// Then:     clear ingestion checkpoints (POST /ingestion/clear-checkpoints or the",
        "//           scripts CLI — see RUNBOOK.md \"Clean-slate reset\") and Run All.",
        "",
        f"USE GRAPH {GRAPH}",
        "",
        "// --- 1. queries (must go before the graph) ---",
    ]
    lines += [f"DROP QUERY {q}" for q in queries]
    lines += [
        "",
        "// --- 2. the graph ---",
        f"DROP GRAPH {GRAPH}",
        "",
        "USE GLOBAL",
        "",
        "// --- 3. reverse edges (separate schema objects; explicit drops required) ---",
    ]
    lines += [f"DROP EDGE {spec['reverse_edge']}" for _n, spec in reversed(list(edges.items()))]
    lines += ["", "// --- 4. forward edges ---"]
    lines += [f"DROP EDGE {name}" for name in reversed(list(edges))]
    lines += ["", "// --- 5. vertices (facts before dimensions) ---"]
    lines += [f"DROP VERTEX {name}" for name in reversed(list(vertices))]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {path}: {len(queries)} queries, {len(edges)} reverse + "
          f"{len(edges)} forward edges, {len(vertices)} vertices")


def main() -> int:
    vertices = parse_vertices((SCHEMA_DIR / "01_vertices.gsql").read_text(encoding="utf-8"))
    edges = parse_edges((SCHEMA_DIR / "02_edges.gsql").read_text(encoding="utf-8"))
    problems = [n for n, s in vertices.items() if not s["primary_id"]]
    problems += [n for n in list(vertices) + list(edges) if not n.startswith(PREFIX)]
    for name, spec in vertices.items():
        if "data_source" not in spec["attributes"]:
            problems.append(f"{name}: missing data_source")
    if problems:
        print("SCHEMA PROBLEMS:", problems)
        return 1
    catalog_path = SCHEMA_DIR.parent / "queries" / "query_catalog.json"
    queries = [q["name"] for q in json.loads(catalog_path.read_text(encoding="utf-8"))["queries"]]
    write_catalog(vertices, edges)
    write_loading_job(vertices, edges)
    write_drop_script(vertices, edges, queries)
    return 0


if __name__ == "__main__":
    sys.exit(main())
